# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bc5c97a048c5d42c2da9a59957b45c87c58fe0ea5fb6ba3b5bbacdfae3e11b85e521723e2d57f31960d75914e6c748d65856a4fb8de6361644b0ea2e514371

test:
  secret_key_base: 5a0fdccabd0eb00aa771cb71e0754857ff9d0a0d19433c707e29add292373d7a75a385a2479548c5fee3717641355383407e23fa76b855ab7222891a1def7fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
